apiVersion: discovery.k8s.io/v1beta1
kind: EndpointSlice
metadata:
  name: demoapp-01
  labels:
    kubernetes.io/service-name: demoapp
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
    - "10.244.101.3"
    conditions:
      ready: true
  - addresses:
    - "10.244.102.6"
    conditions:
      ready: true
